import articulations from './moduleTests/articulations';
import base from './moduleTests/base';
import beam from './moduleTests/beam';
import chord from './moduleTests/chord';
import clef from './moduleTests/clef';
import common from './moduleTests/common';
import duration from './moduleTests/duration';
import dynamics from './moduleTests/dynamics';
import editorial from './moduleTests/editorial';
import figuredBass from './moduleTests/figuredBass';
import interval from './moduleTests/interval';
import iterator from './moduleTests/stream/iterator';
import key from './moduleTests/key';
import meter from './moduleTests/meter';
import note from './moduleTests/note';
import pitch from './moduleTests/pitch';
import prebase from './moduleTests/prebase';
import roman from './moduleTests/roman';
import scale from './moduleTests/scale';
import sites from './moduleTests/sites';
import stream from './moduleTests/stream';
import tempo from './moduleTests/tempo';
import tie from './moduleTests/tie';
import vfShow from './moduleTests/vfShow';
import voiceLeading from './moduleTests/voiceLeading';
declare const allTests: {
    articulations: typeof articulations;
    base: typeof base;
    beam: typeof beam;
    chord: typeof chord;
    clef: typeof clef;
    common: typeof common;
    duration: typeof duration;
    dynamics: typeof dynamics;
    editorial: typeof editorial;
    figuredBass: typeof figuredBass;
    interval: typeof interval;
    iterator: typeof iterator;
    key: typeof key;
    meter: typeof meter;
    note: typeof note;
    pitch: typeof pitch;
    prebase: typeof prebase;
    roman: typeof roman;
    scale: typeof scale;
    sites: typeof sites;
    stream: typeof stream;
    tempo: typeof tempo;
    tie: typeof tie;
    vfShow: typeof vfShow;
    voiceLeading: typeof voiceLeading;
};
export default allTests;
//# sourceMappingURL=loadAll.d.ts.map